DEFAULT_NAMESPACE = 'default'
MONITORING_NAMESPACE = 'monitoring'
ISTIO_NAMESPACE = 'istio-system'
SERVICE_GRAPH_NAMESPACE = 'service-graph'

CLIENT_NODE_POOL_NAME = 'client-pool'
CLIENT_NODE_POOL_MACHINE_TYPE = 'n1-highcpu-16'
CLIENT_JOB_NAME = 'client'
SERVICE_GRAPH_SERVICE_SELECTOR = 'role=service'
